### ISSUE TITLE
Doesn't work after v2.0.0 update.

### ISSUE THREAD

**Issue by AsenCME** [jas-chen/atom-live-server#40]
Sorry to leave such a short comment, but it simply doesn't launch a server, like it used to!

**Comment by PHEDONAS** [comment]
The same here :)

**Comment by jas-chen** [comment]
Keymaps have changed since v2.0.0, have you used the new ones?

**Comment by altamash-ak** [comment]
it stopped working after update i also try the new hotkey and try to launch the server from the packages area but it Doesn't launch
if issue not solved have to uninstall it  :(

**Comment by dane-sd** [comment]
Same issue here. I press all keymaps but that does nothing. Anyway, if I press, for example, ctrl+alt+3 it write me #. I don't know if it is a problem with spanish keyboard. I tried to change keymaps, but still not working. I've also tried to launch server going to Packages > atom-live-server > Start server and nothing happens.

**Comment by paulkiio** [comment]
I too am having issues after the update.

**Comment by jas-chen** [comment]
I just created a new user account on my MacOS, then do a clean install and it worked.

What OS and Atom version are you using?

**Comment by dane-sd** [comment]
In my case, last Atom version in Windows 10.

**Comment by jas-chen** [comment]
Ok, I'll find a Win10 and test on it.

**Comment by jas-chen** [comment]
Have you installed Node.JS on your machine?

**Comment by jas-chen** [comment]
I just published v2.1.0, and it uses atom built-in Node.JS to run the server, please upgrade and give it a try!

**Comment by paulkiio** [comment]
that update worked for me. Thanks jas!

**Comment by chetangulati** [comment]
Failed to spawn command /resources/app/apm/bin/node. Make sure /resources/app/apm/bin/node is installed and on your PATH. It shows this error in v2.1.0 The server does not start. I have also manually checked and the node is there but then also it is not working. I am using Ubuntu 16.04LTS

**Comment by firefoxic** [comment]
> Failed to spawn command /resources/app/apm/bin/node. Make sure /resources/app/apm/bin/node is installed and on your PATH

 I am using ArchLinux (kernel 4.9.8-1-ARCH).

**Comment by MaherFa** [comment]
2.0 was working for me on win 10 x64, I have node installed. 2.0.1 still works.

**Comment by kyovo** [comment]
Same issue and same SO of @chetangulati . Node installed and in the path. 

![image](https://cloud.githubusercontent.com/assets/23282536/22902903/0d0ca624-f237-11e6-9c4c-c2ee036b142c.png)

**Comment by MaherFa** [comment]
issue seems to be the node path
```
const node = path.resolve(
  process.execPath,
  process.platform === 'win32' ? '..' : '../../../../..' ,'resources/app/apm/bin/node'
);
```
it's working on windows so it must be the `'../../../../..'` part
can someone on mac or linux edit _".atom\packages\atom-live-server\lib\atom-live-server.js"_ and test

**Comment by kyovo** [comment]
@MaherFa what should I change?

**Comment by MaherFa** [comment]
`path.resolve` joins multiple parts into a path
`process.execPath` is the path of the atom executable.
every `../` goes up one directory

knowing this, open atoms console and type:
```
path = require('path')
path.resolve(
process.execPath,
  '../../../../..' ,'resources/app/apm/bin/node')
```
you should get the correct path of node, if not then my guess is right and you may compare the path in console to the real path where node is. and add or remove `../` accordingly

**Comment by kyovo** [comment]
this: 
path = require('path')
path.resolve(
process.execPath,
  '../../../../..' ,'resources/app/apm/bin/node')
give me: > resources/app/apm/bin/node

so I remove all the "../" for test in and get this new error.

![image](https://cloud.githubusercontent.com/assets/23282536/22905519/d231dc90-f240-11e6-98b6-33b83f3b4d6b.png)

**Comment by jas-chen** [comment]
Just published v2.1.1, it should fix the problem.

**Comment by chetangulati** [comment]
No Problem remains same for ubuntu

**Comment by firefoxic** [comment]
![default](https://cloud.githubusercontent.com/assets/3382798/22914310/32352ef6-f289-11e6-9087-c3c64e51658b.png)
Node.js v7.5.0
npm v4.2.0
kernel v4.9.8 (ArchLinux)

**Comment by jas-chen** [comment]
What... I tested v2.1.1 on an Ubuntu machine and it worked 😢 .

Linux users, can you find your node path for me? Although I don't think I can support all the Linux distributions.

Or there are other solutions:

1. Run server using system installed Node.JS on Linux(You have to install yourself).
2. Let Linux users to set node path manually.

**Comment by firefoxic** [comment]
Previously it worked. Why was it necessary to change something? Oh…

Where do I need to specify my path `/usr/bin/node`?

**Comment by ashu9394** [comment]
Not working for win7 64 bit . have node installed as well

**Comment by MaherFa** [comment]
it still works for me, never stopped working the last 3 releases.
I start the server using `ctrl+alt+3` or using menu `packages > live-atom-server`

`ctrl + alt + 1` does not work tho

Windows 10 x64, atom latest x64
Node.js installed

atom's node is located in **C:\Users\Maher\AppData\Local\atom\app-1.14.1\resources\app\apm\bin**

**Comment by MaherFa** [comment]
just tested on macOS Sierra v10.12, latest atom and latest live-atom-server. I confirm it works as expected.
live-atom-server
```
path = require('path');
path.resolve(process.env.NODE_PATH, '../../app/apm/bin/node');
```
return the correct path to node (tested in terminal with -v):

`/private/var/folders/3_/z_wts9vj2wvd471kmyk2g8740000gn/T/AppTranslocation/F2461D81-97AE-4F29-B0F5-8C66DE6BC21A/d/Atom.app/Contents/Resources/app/apm/bin/node`

seems to be a linux issue so far.

**Comment by jas-chen** [comment]
But @ashu9394 says it doesn't work in Win7, I will keep investigate it.

**Comment by glennwedin** [comment]
Reinstalled 2.1.1 twice on Ubuntu now and it started working again.

**Comment by ashu9394** [comment]
thanks for all the support @jas-chen , i have reverted back to 1.2.5 that is working perfectly

**Comment by MaherFa** [comment]
just tested on a Win 7 SP1 x64 2.1.1, works perfectly.
I'm not able to get my hands on a machine running linux atm but i'd suggest adding an `fs.existsSync` check for `node ` path on linux os and if it returns false the user is presented with an electron `openFile` `dialog` that stores the path for reuse

or with a message directing on how to add it manually, though a dialog would be much better.

**Comment by Terroristadoomad** [comment]
I think i have the same issue using ATOM BETA as IDE. If you just start ATOM the server launches normally, but if u close the tab on your browser or if u have some runtime errors the server crashes and it does not launch again, u have to restart ATOM to get another server.

i'm using win 7 64bits.
latest version of atom-live-server.

I succesfully replicated the the error on another machine, by just updating the plugin and trying to run.

I suggest ppl to rollback while the issue is not fixed.

**Comment by jas-chen** [comment]
@Terroristadoomad I don't think server will shut down when you close the tab on browsers 😕 

And I'd like to know how you crash the server. May be I can add a `force close server` feature?

**Comment by jas-chen** [comment]
Just tested atom-live-server v2.1.1 on atom v1.15.0-beta3 on macOS 10.12.3, everything works fine...

**Comment by rgdonohue** [comment]
@jas-chen Are we still able to open multiple files in different ports? I can run one file fine, through whatever port I open with control+at+ <port number> on a Mac Sierra. But I seem to need to close the current port to open a different file simultaneously.

Great package!

**Comment by jas-chen** [comment]
@rgdonohue this is not the general way to use this package, I assume that each web project have it's own port. You may consider split different files into different web projects.

I am going to close this issue since the main problem was solved. Thanks for all your feedback and participation.

**Comment by rgdonohue** [comment]
@jas-chen Yes, this is I mean. Currently, if I have two+ projects open in Atom, I can only serve one with atom-live-server through any port. Cntr+alt + <port #> doesn't work until I stop the Live server, move the other project to the top of the sidebar, and then relaunch Live Server.

**Comment by altamash-ak** [comment]
is there is any way to preview PHP live or any other plugin ????

**Comment by PaulRBerg** [comment]
Still doesn't work on OSX, Atom 1.18.0, Node 8.2.1. I get the same **Failed to spawn command**.

**Comment by PaulRBerg** [comment]
Update

I got it working by removing "nuclide" from Atom. I didn't reinstall it to try to see if it continues to work then, but it should, maybe there were some files conflicts.

**Comment by Deus-Rex** [comment]
I managed to fix it by editing the script located in:
`~/.atom/packages/atom-live-server/lib`

I found the location of Node in my system by typing the following in the terminal:
`where node`

then updated this line in the script with the correct path:
`const node = path.resolve('/usr/bin/node');`

This did the trick for me.
